apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
type: Opaque
stringData:
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.notifications.secrets.GOOGLE_OAUTH_CLIENT_ID | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.notifications.secrets.GOOGLE_OAUTH_CLIENT_SECRET | quote }}
  GOOGLE_OAUTH_REFRESH_TOKEN: {{ .Values.notifications.secrets.GOOGLE_OAUTH_REFRESH_TOKEN | quote }}
  SMTP_USER: {{ .Values.notifications.secrets.SMTP_USER | quote }}
