apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.auth.secrets.JWT_SECRET | quote }}
  MONGODB_URI: {{ .Values.auth.secrets.MONGODB_URI | quote }}
