apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: tcp
      port: {{ .Values.auth.env.TCP_PORT }}
      targetPort: {{ .Values.auth.env.TCP_PORT }}
