apiVersion: v1
kind: Service
metadata:
  name: auth-http
spec:
  type: {{ .Values.auth.service.type }}
  selector:
    app: auth
  ports:
    - name: http
      port: {{ .Values.auth.env.HTTP_PORT }}
      targetPort: {{ .Values.auth.env.HTTP_PORT }}
