apiVersion: v1
kind: Service
metadata:
  name: reservations
spec:
  selector:
    app: reservations
  ports:
    - port: {{ .Values.reservations.env.PORT }}
      targetPort: {{ .Values.reservations.env.PORT }}
